### ISSUE TITLE
Python3 Support?

### ISSUE THREAD

**Issue by rsyring** [hmvp/python-tdbus#5]
I'd like to build a backend for the keyring package that uses the dbus Secret Storage interface.  There is already an implementation of this, but it depends on the dbus package which is not pip installable.  I'd like the entire package chain to be manageable by pip.

Anyway, I'd need Python 3 support.  Do you intend to support Python3 anytime soon?

**Comment by hmvp** [comment]
Yes!, look at the p3k branch for progress. I'm not dure hoe long it will take though. I'm accepting pull requests... :-)

**Comment by hmvp** [comment]
So after some checking it seems the p3k branch passes all tests. You do need a development version of gevent though since the main release is not p3 ready.  This should be easy to add as a pip dependency though...
